# Generated by Django 4.2.30 on 2026-09-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=100, verbose_name='آدرس سایت')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن')),
                ('instagram_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس اینستاگرام')),
                ('linkedin_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس لینکدین')),
                ('telegram_url', models.CharField(blank=True, max_length=20, null=True, verbose_name='آدرس تلگرام')),
                ('title_about_medicare', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان درباره مدیکر')),
                ('about_medicare', models.TextField(blank=True, null=True, verbose_name='درباره مدیکر')),
                ('title_mission', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان ماموریت')),
                ('mission', models.TextField(blank=True, null=True, verbose_name='ماموریت')),
                ('why_medicare_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان چرا مدیکر')),
                ('why_medicare', models.TextField(blank=True, null=True, verbose_name='چرا مدیکر')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
