# Generated by Django 4.2.30 on 2026-09-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
