# Generated by Django 4.2.30 on 2026-09-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_module', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='fast_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=100, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال پ غیرفعال')),
            ],
            options={
                'verbose_name': 'لینک سریع',
                'verbose_name_plural': 'لینک های سریع',
            },
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_medicare', models.TextField(blank=True, null=True, verbose_name='درباره مدیکر')),
                ('copyright', models.CharField(blank=True, max_length=150, null=True, verbose_name='قانون کپی رایت')),
                ('fast_link', models.ManyToManyField(to='public_module.fast_link', verbose_name='لینک سریع')),
            ],
            options={
                'verbose_name': 'فوتر',
                'verbose_name_plural': 'فوتر',
            },
        ),
    ]
