# Generated by Django 4.2.30 on 2026-09-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_module', '0004_fast_link_footer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fast_link',
            new_name='FastLink',
        ),
    ]
