# Generated by Django 4.2.30 on 2026-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_module', '0005_rename_fast_link_fastlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
