# Generated by Django 4.2.30 on 2026-09-06 11:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('image', models.ImageField(upload_to='images/specialty', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص ها',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_code', models.CharField(max_length=20, unique=True, verbose_name='شماره نظام پزشکی')),
                ('bio', models.TextField(blank=True, verbose_name='درباره پزشک')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='سابقه کار')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/doctors/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('specialties', models.ManyToManyField(related_name='doctors', to='doctors_module.specialty', verbose_name='تخصص\u200cها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مطب')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('email', models.TextField(blank=True, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با 09 شروع شود و 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='doctors_module.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'مطب',
                'verbose_name_plural': 'مطب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='doctors_module.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'زمان در دسترس',
                'verbose_name_plural': 'زمان\u200cهای در دسترس',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نوبت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأیید شده'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('available_slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='doctors_module.availableslot', verbose_name='زمان نوبت')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors_module.doctor', verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patient.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
            },
        ),
    ]
