# Generated by Django 4.2.30 on 2026-09-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(verbose_name='شماره تماس'),
        ),
    ]
