# Generated by Django 4.2.30 on 2026-09-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0002_alter_clinic_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='url_title',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='نام در url'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='url_title',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='نام در url'),
        ),
    ]
