# Generated by Django 4.2.30 on 2026-09-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0005_alter_clinic_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'تحصیل', 'verbose_name_plural': 'تحصیلات'},
        ),
    ]
