# Generated by Django 4.2.30 on 2026-09-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0007_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_like',
            field=models.CharField(default=False, verbose_name='لایک / دیس لایک'),
        ),
    ]
