# Generated by Django 4.2.30 on 2026-09-08 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors_module', '0008_alter_comment_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_like',
            field=models.BooleanField(default=True, verbose_name='لایک / دیس لایک'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
