# Generated by Django 4.2.30 on 2026-09-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0012_alter_comment_rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_user_doctor_comment',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('user', 'doctor'), name='unique_user_doctor_comment'),
        ),
    ]
