# Generated by Django 4.2.30 on 2026-09-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0013_remove_comment_unique_user_doctor_comment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_user_doctor_comment',
        ),
    ]
