# Generated by Django 4.2.30 on 2026-09-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0014_remove_comment_unique_user_doctor_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('slot_duration', models.PositiveIntegerField(verbose_name='مدت هر نوبت (دقیقه)')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctors_module.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'نوبت دسترس دکتر',
                'verbose_name_plural': 'نوبت های در دسترس دکتر',
            },
        ),
    ]
