# Generated by Django 4.2.30 on 2026-09-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0015_doctoravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('is_available', models.BooleanField(default=False, verbose_name='در دسترس')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='شروع کار')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='پایان کار')),
                ('reason', models.TextField(verbose_name='دلیل')),
            ],
            options={
                'verbose_name': 'استثنای برنامه کاری',
                'verbose_name_plural': 'استثناهای برنامه کاری',
            },
        ),
        migrations.CreateModel(
            name='SchedulePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('duration', models.PositiveIntegerField(help_text='بر حسب دقیقه', verbose_name='مدت هر ویزیت')),
            ],
            options={
                'verbose_name': 'بازه زمانی برنامه',
                'verbose_name_plural': 'بازه\u200cهای زمانی برنامه',
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه\u200cهای هفتگی',
            },
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='available_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors_module.availableslot', verbose_name='زمان نوبت'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('available_slot',), name='unique_active_appointment_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='availableslot',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'start_time'), name='unique_doctor_slot'),
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='doctors_module.doctor', verbose_name='پزشک'),
        ),
        migrations.AddField(
            model_name='scheduleperiod',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='doctors_module.weeklyschedule', verbose_name='برنامه هفتگی'),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='doctors_module.doctor', verbose_name='دکتر'),
        ),
        migrations.AddConstraint(
            model_name='weeklyschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'weekday'), name='unique_doctor_weekday'),
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.UniqueConstraint(fields=('doctor', 'date'), name='unique_doctor_exception_date'),
        ),
    ]
