# Generated by Django 4.2.30 on 2026-09-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0016_scheduleexception_scheduleperiod_weeklyschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleexception',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='بر حسب دقیقه', null=True, verbose_name='مدت هر ویزیت'),
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='doctors_module.doctor', verbose_name='پزشک'),
        ),
    ]
