# Generated by Django 4.2.30 on 2026-09-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0017_scheduleexception_duration_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_appointment_per_slot',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'completed'])), fields=('available_slot',), name='unique_active_appointment_per_slot'),
        ),
    ]
