# Generated by Django 4.2.30 on 2026-09-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0019_province_clinic_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'خانم'), ('prefer not to say', 'ترجیح میدم نگویم')], max_length=50, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='doctors_module.province', verbose_name='استان'),
        ),
    ]
