# Generated by Django 4.2.30 on 2026-09-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0020_doctor_gender_alter_clinic_province'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scheduleperiod',
            constraint=models.UniqueConstraint(fields=('schedule', 'start_time', 'end_time'), name='unique_schedule_period'),
        ),
    ]
