# Generated by Django 4.2.30 on 2026-09-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0021_scheduleperiod_unique_schedule_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='user_type',
            field=models.CharField(blank=True, choices=[('citizen', 'شهروند'), ('doctor', 'پزشک')], default='citizen', max_length=20, null=True, verbose_name='مخاطب'),
        ),
    ]
