# Generated by Django 4.2.30 on 2026-09-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0022_faq_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='یادآوری ارسال شده'),
        ),
    ]
