# Generated by Django 4.2.30 on 2026-09-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('doctors_module', '0017_scheduleexception_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authority')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='patient.patient', verbose_name='بیمار')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='doctors_module.availableslot', verbose_name='زمان نوبت')),
            ],
        ),
    ]
