# Generated by Django 4.2.30 on 2026-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='مبلغ به ریال', verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه تراکنش'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
