# Generated by Django 4.2.30 on 2026-09-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0002_alter_payment_amount_alter_payment_authority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت ها'},
        ),
    ]
