# Generated by Django 4.2.30 on 2026-09-17 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=100, verbose_name='عبارت جستجو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ جستجو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جستجوی اخیر',
                'verbose_name_plural': 'جستجوهای اخیر',
                'ordering': ['-created_at'],
            },
        ),
    ]
