# Generated by Django 4.2.30 on 2026-09-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_module', '0021_scheduleperiod_unique_schedule_period'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='doctors_module.doctor', verbose_name='دکتر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_doctors', to='patient.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'علاقه مندی',
                'verbose_name_plural': 'علاقه مندی ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='favoritedoctor',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_favorite_doctor'),
        ),
    ]
