# Generated by Django 4.2.30 on 2026-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatar', verbose_name='عکس کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='family',
            field=models.CharField(max_length=50, verbose_name='نام خانوداگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
    ]
