# Generated by Django 4.2.30 on 2026-09-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_avatar_alter_user_family_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال کد فعال سازی'),
        ),
    ]
