# Generated by Django 4.2.30 on 2026-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_user_verification_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='کد فعال سازی فراموشی رمز عبور'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ کد فعال سازی فراموشی رمز عبور'),
        ),
    ]
