# Generated by Django 4.2.30 on 2026-09-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='family',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
